notifiers:
  - name: teams-grafana-notifier
    type: teams
    uid: teams
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      url: ${TEAMS_WEBHOOK_URL}
