apiVersion: v1
kind: Namespace
metadata:
  name: lynus
  labels:
    name: lynus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-reader
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-reader-lynus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: lynus
