apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventwatcher
  namespace: lynus
  labels:
    app: eventwatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventwatcher
  template:
    metadata:
      labels:
        app: eventwatcher
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: eventwatcher
          image: ghcr.io/eneries/eneries/eventwatcher:TAG
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "4096Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_ADDRESS
                  name: lynus-credentials
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PORT
                  name: lynus-credentials
            - name: DB_NAME
              value: lynus
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: lynus-credentials
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: lynus-credentials
            - name: DB_MODE
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_SSLMODE
                  name: lynus-credentials
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  key: REDIS_ADDRESS
                  name: lynus-credentials
            - name: MQTT_ADDR
              valueFrom:
                secretKeyRef:
                  key: MOSQUITTO_ADDRESS
                  name: lynus-credentials
            - name: OEAMTC_EVENT_HUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: OEAMTC_EVENT_HUB_CONNECTION_STRING
                  name: lynus-credentials
            - name: OQDO_SIGNALR_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: OQDO_SIGNALR_CONNECTION_STRING
                  name: lynus-credentials
            - name: EASEE_AMQP_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: EASEE_AMQP_CONNECTION_STRING
                  name: lynus-credentials
      nodeSelector:
        nodetype: large
---
apiVersion: v1
kind: Service
metadata:
  name: eventwatcher
  namespace: lynus
spec:
  selector:
    app: eventwatcher
  ports:
    - port: 8000
      targetPort: 8000
      name: metrics
  type: ClusterIP
