apiVersion: v1
data:
  .dockerconfigjson: DOCKERCONFIGJSON_VALUE
kind: Secret
metadata:
  name: ghcr
  namespace: lynus
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: lynus-credentials
  namespace: lynus
data:
  KEYCLOAK_PASSWORD: KEYCLOAK_PASSWORD_VALUE
  KEYCLOAK_USERNAME: KEYCLOAK_USERNAME_VALUE
  MINIO_PASSWORD: MINIO_PASSWORD_VALUE
  MINIO_USERNAME: MINIO_USERNAME_VALUE
  OPENWEATHERMAP_KEY: OPENWEATHERMAP_KEY_VALUE
  POSTGRES_ADDRESS: POSTGRES_ADDRESS_VALUE
  POSTGRES_PORT: POSTGRES_PORT_VALUE
  POSTGRES_PASSWORD: POSTGRES_PASSWORD_VALUE
  POSTGRES_USERNAME: POSTGRES_USERNAME_VALUE
  POSTGRES_SSLMODE: POSTGRES_SSLMODE_VALUE
  MOSQUITTO_ADDRESS: MOSQUITTO_ADDRESS_VALUE
  REDIS_ADDRESS: REDIS_ADDRESS_VALUE
  SENDGRID_CONFIGS: SENDGRID_CONFIGS_VALUE
  EMPA_PASSWORD: EMPA_PASSWORD_VALUE
  METEOTEST_API_KEY: METEOTEST_API_KEY_VALUE
  ADMIN_CONSOLE_PASSWORD: ADMIN_CONSOLE_PASSWORD_VALUE
  GRAFANA_ADMIN_PASSWORD: GRAFANA_ADMIN_PASSWORD_VALUE
  OEAMTC_EVENT_HUB_CONNECTION_STRING: OEAMTC_EVENT_HUB_CONNECTION_STRING_VALUE
  OQDO_SIGNALR_CONNECTION_STRING: OQDO_SIGNALR_CONNECTION_STRING_VALUE
  EASEE_AMQP_CONNECTION_STRING: EASEE_AMQP_CONNECTION_STRING_VALUE
  DOMAIN: DOMAIN_VALUE
  GPS_TOKEN: GPS_TOKEN_VALUE
  CLUSTER_NAME: CLUSTER_NAME_VALUE
  S3_SECRET_KEY: S3_SECRET_KEY_VALUE
  S3_ACCESS_KEY: S3_ACCESS_KEY_VALUE
  S3_URL: S3_URL_VALUE
  TEAMS_WEBHOOK_URL: TEAMS_WEBHOOK_URL_VALUE
---
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: tls-certificates
  namespace: lynus
data:
  tls.crt: TLS_CRT_VALUE
  tls.key: TLS_KEY_VALUE
  mqtt.crt: MQTT_CRT_VALUE
  mqtt.key: MQTT_KEY_VALUE
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ENDPOINTS: S3_BACKUP_ENDPOINT_VALUE
  AWS_ACCESS_KEY_ID: S3_BACKUP_KEY_VALUE
  AWS_SECRET_ACCESS_KEY: S3_BACKUP_SECRET_VALUE
  AWS_BACKUP_TARGET: S3_BACKUP_TARGET_VALUE
---
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: mqtt-certificates
  namespace: lynus
data:
  tls.crt: MQTT_CRT_VALUE
  tls.key: MQTT_KEY_VALUE
