apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: console-preview-certificate-store-TAG
  namespace: lynus
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-preview-TAG
  namespace: lynus
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-preview-TAG
  template:
    metadata:
      labels:
        app: console-preview-TAG
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: console
          image: ghcr.io/eneries/eneries/console:TAG
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - mountPath: /certs
              name: data
          imagePullPolicy: Always
          env:
            - name: ENABLE_HTTP
              value: "true"
      nodeSelector:
        nodetype: large
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: console-preview-certificate-store-TAG
---
apiVersion: v1
kind: Service
metadata:
  name: console-preview-TAG-service
  namespace: lynus
spec:
  selector:
    app: console-preview-TAG
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
    kubernetes.io/ingress.class: nginx
  name: console-preview-TAG-ingress
  namespace: lynus
spec:
  ingressClassName: nginx
  rules:
    - host: console-preview-TAG.dev.$DOMAIN
      http:
        paths:
          - backend:
              service:
                name: console-preview-TAG-service
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - console-preview-TAG.dev.$DOMAIN
      secretName: console-preview-TAG-tls-secret
