apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lynus
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: api
          image: ghcr.io/efficientio/efficientio/api:TAG
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_ADDRESS
                  name: lynus-credentials
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PORT
                  name: lynus-credentials
            - name: DB_NAME
              value: lynus
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: lynus-credentials
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: lynus-credentials
            - name: DB_MODE
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_SSLMODE
                  name: lynus-credentials
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  key: REDIS_ADDRESS
                  name: lynus-credentials
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  key: DOMAIN
                  name: lynus-credentials
            - name: MINIO_SSL
              value: "true"
            - name: MINIO_ADDR
              value: s3.$(DOMAIN)
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: MINIO_USERNAME
                  name: lynus-credentials
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: MINIO_PASSWORD
                  name: lynus-credentials
            - name: KEYCLOAK_ADDR
              value: http://keycloak
            - name: KEYCLOAK_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_USERNAME
                  name: lynus-credentials
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_PASSWORD
                  name: lynus-credentials
            - name: OPENWEATHERMAP_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENWEATHERMAP_KEY
                  name: lynus-credentials
            - name: SENDGRID_CONFIGS
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_CONFIGS
                  name: lynus-credentials
            - name: REPORT_ADDR
              value: report:80
            - name: MQTT_ADDR
              valueFrom:
                secretKeyRef:
                  key: MOSQUITTO_ADDRESS
                  name: lynus-credentials
            - name: MPC_ADDR
              value: http://mpc
            - name: GPS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GPS_TOKEN
                  name: lynus-credentials
            - name: EASEE_AMQP_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: EASEE_AMQP_CONNECTION_STRING
                  name: lynus-credentials
      nodeSelector:
        nodetype: large
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: lynus
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
