name: github_secrets_ci_cd

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: export the secrets
        shell: python
        run: |
          secrets_context = """${{ toJson(secrets) }}""".strip()
          open('secrets.json', 'w').write(secrets_context)
      - name: upload the secrets
        uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets.json
